

type AccountType {
    _id: ID
    idUser: ID
}
# Account Type

# Account Input
input IAccount {
    _id: ID
    idUser: ID
}
enum typeAccount {
  ASSETS,
  EXPENSE,
  LIABILITY,
  INCOME,
}
type Query {
  HelloWord: String
}

# Mutations
type Mutation {
  registerAccount(input: IAccount): AccountType
}
